made Book-model, repository and sevice
DPotapov93/OnlineBookStore pull request #1
Opened 2023-12-04 16:15 UTC by DPotapov93

2023-12-04 16:49 UTC, vovasalyha requested changes
Looks fine, but please add a CommandLineRunner bean with usage of a book service as described in HW requirements

2023-12-04 17:17 UTC, DPotapov93 commented on checkstyle.xml
> +</module>
if I understand right, it was already in the main method automatically

2023-12-05 07:17 UTC, bhdnchui requested changes
Good job! Just one minor point to consider.
Also, pay attention you have not any CommandLineRunner bean realization with sample of usage BookService.

2023-12-05 07:17 UTC, bhdnchui commented on src/main/java/mate/academy/onlinebookstore01/model/Book.java
> +public class Book {
It would be great to add `@Table` annotation and define the table name.

2023-12-05 07:17 UTC, bhdnchui commented on src/main/java/mate/academy/onlinebookstore01/OnlineBookStore01Application.java
>      }
Please, add `CommandLineRunner` bean in accordance with the task requirements.
<img width="862" alt="image" src="https://github.com/DPotapov93/OnlineBookStore/assets/140437083/ed47bc2d-a985-4722-886f-82d0e4734371">

2023-12-05 13:00 UTC, kshuryhin approved these changes
Looks good

2023-12-06 07:37 UTC, merged