Implementing dto`s classes
DPotapov93/OnlineBookStore pull request #2
Opened 2023-12-10 18:11 UTC by DPotapov93

2023-12-11 12:17 UTC, DevIgork approved these changes
I think you did a good job.

2023-12-11 16:16 UTC, bhdnchui requested changes
Please, pay attention to my comments.

2023-12-11 16:16 UTC, bhdnchui commented on pom.xml
> +    <artifactId>book-shop</artifactId>
That task requires such significant changes.
Please, make changes that are required by task only.

2023-12-11 16:16 UTC, bhdnchui commented on src/main/java/mate/academy/onlinebookstore01/controller/BookController.java
> +    @GetMapping("/api/books/{id}")
You already defined `/api/books` part in `@RequestMapping` annotation.
Did you test your solution?
```suggestion
    @GetMapping("/{id}")
```

2023-12-11 16:16 UTC, bhdnchui commented on src/main/java/mate/academy/onlinebookstore01/service/BookServiceImpl.java
> +        return bookMapper.toDto(book);
Where is `bookRepository.save()` method call?

2023-12-11 16:16 UTC, bhdnchui commented on src/main/java/mate/academy/onlinebookstore01/service/BookServiceImpl.java
> +        return bookMapper.toDto(book);
Rewrite it and avoid redundant temporary `Book book` variable.

2023-12-12 09:45 UTC, d1sam approved these changes
Well done, but be careful with unnecessary variables.

2023-12-12 09:45 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore01/repository/BookRepositoryImpl.java
> +            return Optional.ofNullable(book);
```suggestion
            return Optional.ofNullable(session.find(Book.class, id));
```

2023-12-13 11:58 UTC, merged