iplemented CustomGlobalExceptionHandler class and added meaningful va…
DPotapov93/OnlineBookStore pull request #4
Opened 2023-12-15 14:00 UTC by DPotapov93

…lidation

2023-12-18 10:53 UTC, forzen123212 approved these changes
Good job, just some minor changes are need to be added

2023-12-18 10:53 UTC, forzen123212 commented on src/main/java/mate/academy/onlinebookstore01/dto/CreateBookRequestDto.java
> +    @NotNull
Add min and max length

2023-12-18 10:53 UTC, forzen123212 commented on src/main/java/mate/academy/onlinebookstore01/dto/CreateBookRequestDto.java
> +    @NotNull
same

2023-12-19 11:27 UTC, d1sam requested changes
Looks good, but see a couple of comments.

2023-12-19 11:27 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore01/exception/CustomGlobalExceptionHandler.java
Please also handle your own `EntityNotFoundException.class`

2023-12-19 11:27 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore01/exception/CustomGlobalExceptionHandler.java
> +        body.put("errors", errors);
String literals can be as constants

2023-12-19 11:27 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore01/dto/CreateBookRequestDto.java
> +    @Min(0)
```suggestion
    @Positive
```

2023-12-19 11:27 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore01/dto/CreateBookRequestDto.java
> +    @Size(min = 10, max = 13)
ISBN has fixed format, you can use [Hibernate validators](https://www.baeldung.com/hibernate-validator-constraints) or rewrite your regexp by [this](https://howtodoinjava.com/java/regex/java-regex-validate-international-standard-book-number-isbns/) guide

2023-12-19 11:27 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore01/dto/CreateBookRequestDto.java
>      private String title;
I would also validate a maximum size of text fields, to not exceed the DB column restrictions.

2023-12-19 11:27 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore01/dto/CreateBookRequestDto.java
>      private String author;
I would also validate a maximum size of text fields, to not exceed the DB column restrictions.

2023-12-19 11:27 UTC, d1sam commented on src/main/java/mate/academy/onlinebookstore01/dto/CreateBookRequestDto.java
Also provide custom messages to validation annotations

2023-12-19 13:06 UTC, vovasalyha approved these changes

2023-12-19 14:20 UTC, merged